# Generated by Django 6.0.2 on 2026-02-03 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('date_fermeture', models.DateTimeField(verbose_name='Date de fermeture')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('fermé', 'Fermé')], default='ouvert', max_length=10, verbose_name='Statut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_ouverture'],
            },
        ),
    ]
