# Generated by Django 6.0.2 on 2026-02-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_fermeture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture'),
        ),
    ]
