# Generated by Django 6.0.2 on 2026-02-03 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_date_fermeture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validé', 'Validé'), ('refusé', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_validation', models.DateTimeField(auto_now_add=True, verbose_name='Date de validation')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.action', verbose_name='Action')),
                ('validateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': 'Validation',
                'verbose_name_plural': 'Validations',
                'ordering': ['-date_validation'],
            },
        ),
    ]
