# Generated by Django 6.0.2 on 2026-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='categorie',
            field=models.CharField(choices=[('panne', 'Panne'), ('maintenance', 'Maintenance'), ('incident', 'Incident'), ('suivi', 'Suivi'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='action',
            name='cause',
            field=models.TextField(blank=True, null=True, verbose_name='Cause supposée ou identifiée'),
        ),
        migrations.AddField(
            model_name='action',
            name='personnes_impliquees',
            field=models.TextField(blank=True, null=True, verbose_name='Personnes impliquées'),
        ),
        migrations.AddField(
            model_name='action',
            name='statut',
            field=models.CharField(choices=[('resolu', 'Résolu'), ('en_attente', 'En attente'), ('en_cours', 'En cours')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='action',
            name='suivi',
            field=models.BooleanField(default=False, verbose_name='Nécessite un suivi'),
        ),
    ]
